// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.ymou.grpc;

/**
 * Protobuf enum {@code Sentiment}
 */
public enum Sentiment
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HAPPY = 0;</code>
   */
  HAPPY(0),
  /**
   * <code>ANGRY = 1;</code>
   */
  ANGRY(1),
  /**
   * <code>SLEEPY = 3;</code>
   */
  SLEEPY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>HAPPY = 0;</code>
   */
  public static final int HAPPY_VALUE = 0;
  /**
   * <code>ANGRY = 1;</code>
   */
  public static final int ANGRY_VALUE = 1;
  /**
   * <code>SLEEPY = 3;</code>
   */
  public static final int SLEEPY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Sentiment valueOf(int value) {
    return forNumber(value);
  }

  public static Sentiment forNumber(int value) {
    switch (value) {
      case 0: return HAPPY;
      case 1: return ANGRY;
      case 3: return SLEEPY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Sentiment>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Sentiment> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Sentiment>() {
          public Sentiment findValueByNumber(int number) {
            return Sentiment.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ymou.grpc.HelloServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final Sentiment[] VALUES = values();

  public static Sentiment valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Sentiment(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Sentiment)
}

